name: ci

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'

jobs:
  docker:
    strategy:
      matrix:
        ubuntu-release:
          - "20.04"
        jdk-release:
          - "17"
    env:
      IMAGE_REPO: itzg/ubuntu-remote-dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          build-args: |
            BASE_IMG=ubuntu:${{ matrix.ubuntu-release }}
            JDK_RELEASE=${{ matrix.jdk-release }}
          tags: ${{ env.IMAGE_REPO }}:${{ matrix.ubuntu-release }}-${{ matrix.jdk-release }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
